# Generated by Django 6.0.7 on 2026-08-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_documents',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='max_storage_bytes',
            field=models.BigIntegerField(default=524288000),
        ),
        migrations.CreateModel(
            name='QuotaChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_max_documents', models.IntegerField()),
                ('new_max_documents', models.IntegerField()),
                ('old_max_storage_bytes', models.BigIntegerField()),
                ('new_max_storage_bytes', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
