# Generated by Django 6.0.7 on 2026-08-16 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_max_documents_user_max_storage_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotachangelog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotachangelog',
            name='new_max_documents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotachangelog',
            name='new_max_storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotachangelog',
            name='old_max_documents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotachangelog',
            name='old_max_storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
