# Generated by Django 6.0.7 on 2026-08-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_hash_document_file_size'),
        ('knowledge', '0003_quiz_question_quizattempt_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='concept',
            field=models.CharField(blank=True, help_text='Core concept being tested', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='documents.document'),
        ),
    ]
