# Generated by Django 6.0.7 on 2026-08-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_question_concept_alter_quiz_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('open', 'Open Question')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, related_name='sourced_questions', to='knowledge.documentchunk'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='feedback',
            field=models.TextField(blank=True, help_text='LLM feedback for open answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of possible answers (empty for open questions)'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='user_answer',
            field=models.TextField(),
        ),
    ]
