# Generated by Django 6.0.7 on 2026-08-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_hash_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Set when status=FAILED, describes what went wrong'),
        ),
    ]
